### ISSUE TITLE
Add effect or color when enemy is hit

### ISSUE THREAD

**Issue by kalkoka** [StefanoPruna/FantasyKitties#1]
can we add an effect or colour when the enemy is hit? maybe something like this:

GetComponent<SpriteRenderer>().color = new Color(1f,0.30196078f, 0.30196078f);

**Comment by StefanoPruna** [comment]
Alright let's add it

**Comment by kalkoka** [comment]
found this snippet, give it a shot:

 public float flashTime;
 Color origionalColor
 public MeshRenderer renderer;
 void Start()
 {
     origionalColor = renderer.color;
 }
 void FlashRed()
 {
     renderer.color = Color.red;
     Invoke("ResetColor", flashTime);
 }
 void ResetColor()
 {
      renderer.color = origionalColor;
 }

**Comment by kalkoka** [comment]
done and closing the issue now.
